name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy gh-pages
        run: npm run deploy
        
  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #   - name: Download artifact
  #     uses: actions/download-artifact@v4.1.8
  #     with:
  #       name: production-files
  #       path: ./dist
